name: B_AMA
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - ipykernel
  - nbconvert
  - nbformat
  - notebook
  - jupyterlab
  - dill
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - scikit-learn
  - pip:
    - hydroeval
